version: '4.1'
package:
  name: 5gtango-project-sample
  vendor: eu.5gtango
  version: '0.1'
  maintainer: Name, Company, Contact
  description: Some description about this sample
  uuid: 84cadef0-2062-42e4-8cef-5ddedd4a7249
descriptor_extension: yml
files:
- path: osm_nsd.yml
  type: application/vnd.etsi.osm.nsd
  tags:
  - etsi.osm
- path: osm_vnfd0.yml
  type: application/vnd.etsi.osm.vnfd
  tags:
  - etsi.osm
- path: tango_nsd.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
- path: tango_vnfd0.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
